---
title: 'Lab 3 - Parte 2: Prevendo Evasão'
author: "Luiz Fonseca"
date: "20 de fevereiro de 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(reshape2)
library(dplyr)
library(caret)

dados <- read.csv("../data/treino_classificacao.csv")
names(dados) <- c("matricula", "cod_disciplina", "disciplina", "ano", "periodo", "media", "evadiu")

medias.abaixo.7 <- function(medias) {
  temp <- medias[medias < 7]
  return(length(temp))
}

dados <- dados %>%
  group_by(matricula) %>%
  mutate(medias_abaixo_7 = medias.abaixo.7(media))

train.data <- dados %>% filter(ano >= 2010, ano != 2015)
test.data <- dados %>% filter(ano == 2015)

convert.data.to.model.input <- function(dataframe) {
  dataframe <- dataframe %>% select(-cod_disciplina, -periodo, -ano) %>% filter(!is.na(media))
  
  alunos.evadiu <- dataframe %>%
    group_by(matricula) %>%
    summarise(evadiu = any(evadiu),
              medias_abaixo_7 = mean(medias_abaixo_7))
    
  model.input <- dataframe %>%
    group_by(matricula, disciplina)  %>%
    filter(media == max(media)) %>%
    ungroup() %>%
    select(matricula, disciplina, media) %>% 
    mutate(disciplina = as.factor(gsub(" ",".",disciplina))) %>%
    dcast(matricula ~ disciplina, mean) %>%
    merge(alunos.evadiu)
  
  model.input$evadiu <- as.factor(model.input$evadiu)
  return(model.input)
}

train.data <- train.data %>% convert.data.to.model.input()
test.data <- test.data %>% convert.data.to.model.input()

# Treine modelos de regressão logística;

glm.fit <- train(evadiu ~ . -matricula,
                 data=train.data,
                 method="glm",
                 family="binomial",
                 na.action = na.omit)

x <- predict(glm.fit, newdata=test.data)
```

